{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Untitled1.ipynb의 사본",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyPAQxRaMP1dvsHIn5DS+WcH"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "87eZAjZAuQ0S",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "235cb7cf-00a4-4ffb-c687-ffafa7a572f7"
      },
      "source": [
        "!pip install telepot\n",
        "!pip install pymysql\n",
        "import telepot\n",
        "from telepot.loop import MessageLoop\n",
        "\n",
        "import datetime\n",
        "import requests\n",
        "import bs4\n",
        "import pandas as pd\n",
        "import pymysql\n",
        "import json\n",
        "\n",
        "bot = telepot.Bot('1884421658:AAFVbe7QVpSt2m7auQccrUUyO-Qsvnk0IwA')\n",
        "\n",
        "\n",
        "def Crawling():    \n",
        "    r = requests.get('https://api.btctools.io/api/leaderboard')\n",
        "    html = r.text\n",
        "    tmp = json.loads(html)\n",
        "    a = pd.DataFrame.from_dict(tmp['data'])\n",
        "    return a\n",
        "\n",
        "def Chatbot(msg):\n",
        "    content_type, chat_type, chat_id, msg_date, msg_id = telepot.glance(msg, long=True)\n",
        "    print(msg)\n",
        "    df_rankerSide=Crawling()\n",
        "    sendMsg=str(datetime.datetime.fromtimestamp(int(df_rankerSide['timestamp'][0])))+'\\n'+str(df_rankerSide['side'].value_counts())\n",
        "    bot.sendMessage(chat_id,sendMsg)\n",
        "    \n",
        "def main():\n",
        "    \n",
        "    MessageLoop(bot, Chatbot).run_forever()\n",
        "    print('ok')\n",
        "\n",
        "def saveSide(time):\n",
        "    print('ok')\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    main()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Collecting telepot\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/f6/a8/0ed945afd8064b850c1653816c16ebda1cf07d65fee228b6d1139a49cbbd/telepot-12.7.tar.gz (73kB)\n",
            "\r\u001b[K     |████▌                           | 10kB 15.5MB/s eta 0:00:01\r\u001b[K     |█████████                       | 20kB 8.6MB/s eta 0:00:01\r\u001b[K     |█████████████▍                  | 30kB 7.2MB/s eta 0:00:01\r\u001b[K     |██████████████████              | 40kB 7.1MB/s eta 0:00:01\r\u001b[K     |██████████████████████▍         | 51kB 3.0MB/s eta 0:00:01\r\u001b[K     |██████████████████████████▉     | 61kB 3.2MB/s eta 0:00:01\r\u001b[K     |███████████████████████████████▍| 71kB 3.3MB/s eta 0:00:01\r\u001b[K     |████████████████████████████████| 81kB 2.8MB/s \n",
            "\u001b[?25hRequirement already satisfied: urllib3>=1.9.1 in /usr/local/lib/python3.7/dist-packages (from telepot) (1.24.3)\n",
            "Collecting aiohttp>=3.0.0\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/88/c0/5890b4c8b04a79b7360e8fe4490feb0bb3ab179743f199f0e6220cebd568/aiohttp-3.7.4.post0-cp37-cp37m-manylinux2014_x86_64.whl (1.3MB)\n",
            "\u001b[K     |████████████████████████████████| 1.3MB 9.5MB/s \n",
            "\u001b[?25hRequirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.0.0->telepot) (3.7.4.3)\n",
            "Collecting yarl<2.0,>=1.0\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/f1/62/046834c5fc998c88ab2ef722f5d42122230a632212c8afa76418324f53ff/yarl-1.6.3-cp37-cp37m-manylinux2014_x86_64.whl (294kB)\n",
            "\u001b[K     |████████████████████████████████| 296kB 43.8MB/s \n",
            "\u001b[?25hCollecting async-timeout<4.0,>=3.0\n",
            "  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl\n",
            "Collecting multidict<7.0,>=4.5\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/7c/a6/4123b8165acbe773d1a8dc8e3f0d1edea16d29f7de018eda769abb56bd30/multidict-5.1.0-cp37-cp37m-manylinux2014_x86_64.whl (142kB)\n",
            "\u001b[K     |████████████████████████████████| 143kB 51.0MB/s \n",
            "\u001b[?25hRequirement already satisfied: chardet<5.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.0.0->telepot) (3.0.4)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=3.0.0->telepot) (21.2.0)\n",
            "Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp>=3.0.0->telepot) (2.10)\n",
            "Building wheels for collected packages: telepot\n",
            "  Building wheel for telepot (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for telepot: filename=telepot-12.7-cp37-none-any.whl size=57962 sha256=d25dbd7b26d79bf74631137ddb4d24c41bdf8d30db41d68b5ab96668dbfe1455\n",
            "  Stored in directory: /root/.cache/pip/wheels/65/17/50/983034e27e6b5d8dfc497a51b5b13d970d8018a83f47e6513a\n",
            "Successfully built telepot\n",
            "Installing collected packages: multidict, yarl, async-timeout, aiohttp, telepot\n",
            "Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 multidict-5.1.0 telepot-12.7 yarl-1.6.3\n",
            "Collecting pymysql\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/4f/52/a115fe175028b058df353c5a3d5290b71514a83f67078a6482cff24d6137/PyMySQL-1.0.2-py3-none-any.whl (43kB)\n",
            "\u001b[K     |████████████████████████████████| 51kB 3.7MB/s \n",
            "\u001b[?25hInstalling collected packages: pymysql\n",
            "Successfully installed pymysql-1.0.2\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/loop.py\", line 60, in run_forever\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
            "    return self._api_request('getUpdates', _rectify(p))\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/__init__.py\", line 491, in _api_request\n",
            "    return api.request((self._token, method, params, files), **kwargs)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 155, in request\n",
            "    return _parse(r)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/telepot/api.py\", line 150, in _parse\n",
            "    raise exception.TelegramError(description, error_code, data)\n",
            "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
          ],
          "name": "stderr"
        }
      ]
    }
  ]
}